# -*- coding: utf-8 -*-
"""PDF2Image2Text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LFxeB0qizGGN3Nw4eDaHYlFZhGxgH5zS
"""

!apt-get install poppler-utils
!pip install pdf2image
!pip install pytesseract

from pdf2image import convert_from_path
from PIL import Image
import pytesseract
import os
from tqdm import tqdm

!apt-get install tesseract-ocr
!apt-get install libtesseract-dev

pdf_path = 'merge.pdf'

output_folder = 'pdf_images'
os.makedirs(output_folder, exist_ok=True)

try:
    pages = convert_from_path(pdf_path, dpi=300)
except Exception as e:
    print(f"Error converting PDF to images: {e}")
    quit()

extracted_text = []
for i, page in enumerate(tqdm(pages, desc='Processing pages')):
    image_path = os.path.join(output_folder, f'page_{i+1}.png')
    page.save(image_path, 'PNG')

    try:
        text = pytesseract.image_to_string(Image.open(image_path))
        extracted_text.append(text)
    except Exception as e:
        print(f"Error extracting text from image {i+1}: {e}")

    os.remove(image_path)

full_text = "\n\n".join(extracted_text)

with open('extracted_text.txt', 'w', encoding='utf-8') as f:
    f.write(full_text)

print("Text extraction complete. The extracted text is saved in 'extracted_text.txt'.")

